"""USD asset generation module.

Uses OpenUSD Python bindings (pxr) when available; falls back to a minimal
hand-written .usda string template so the service stays functional without a
full OpenUSD install.
"""

from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Optional pxr import with graceful fallback
# ---------------------------------------------------------------------------

try:
    from pxr import Gf, Usd, UsdGeom  # type: ignore[import]

    _PXR_AVAILABLE = True
except ImportError:
    _PXR_AVAILABLE = False


# ---------------------------------------------------------------------------
# Storage directory
# ---------------------------------------------------------------------------

ASSETS_DIR = Path("/tmp/usdagent-assets")


def _ensure_assets_dir() -> None:
    ASSETS_DIR.mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------------------------------
# Shape detection
# ---------------------------------------------------------------------------

_SHAPE_KEYWORDS: dict[str, list[str]] = {
    "sphere": ["sphere", "ball", "orb", "globe", "round"],
    "cylinder": ["cylinder", "tube", "pipe", "column", "pillar", "barrel"],
    "box": ["box", "cube", "block", "crate", "rectangular", "square"],
}


def _detect_shape(description: str) -> str:
    """Return the best-matching primitive shape for the description."""
    lower = description.lower()
    for shape, keywords in _SHAPE_KEYWORDS.items():
        if any(kw in lower for kw in keywords):
            return shape
    return "box"  # default


# ---------------------------------------------------------------------------
# pxr-based generation
# ---------------------------------------------------------------------------


def _generate_with_pxr(
    asset_id: str,
    description: str,
    options: dict[str, Any],
) -> Path:
    """Generate a USD file using the pxr library."""
    shape = _detect_shape(description)
    out_path = ASSETS_DIR / f"{asset_id}.usda"

    stage = Usd.Stage.CreateNew(str(out_path))

    # Stage-level metadata
    UsdGeom.SetStageUpAxis(stage, options.get("up_axis", "Y"))
    stage.SetMetadata("metersPerUnit", _units_to_meters(options.get("units", "centimeters")))
    stage.SetMetadata("comment", f"Generated by usdagent from: {description}")

    scale = float(options.get("scale", 1.0))

    if shape == "sphere":
        prim = UsdGeom.Sphere.Define(stage, "/Asset/Sphere")
        prim.GetRadiusAttr().Set(50.0 * scale)
    elif shape == "cylinder":
        prim = UsdGeom.Cylinder.Define(stage, "/Asset/Cylinder")
        prim.GetRadiusAttr().Set(25.0 * scale)
        prim.GetHeightAttr().Set(100.0 * scale)
    else:  # box
        prim = UsdGeom.Cube.Define(stage, "/Asset/Cube")
        prim.GetSizeAttr().Set(100.0 * scale)

    # Apply extent
    extent_attr = prim.GetExtentAttr()
    half = 50.0 * scale
    extent_attr.Set([Gf.Vec3f(-half, -half, -half), Gf.Vec3f(half, half, half)])

    stage.SetDefaultPrim(stage.GetPrimAtPath("/Asset"))
    stage.GetRootLayer().Save()
    return out_path


def _units_to_meters(units: str) -> float:
    mapping = {
        "meters": 1.0,
        "centimeters": 0.01,
        "millimeters": 0.001,
        "inches": 0.0254,
        "feet": 0.3048,
    }
    return mapping.get(units.lower(), 0.01)


# ---------------------------------------------------------------------------
# Fallback string-template generation
# ---------------------------------------------------------------------------

_USDA_TEMPLATES: dict[str, str] = {
    "box": """\
#usda 1.0
(
    defaultPrim = "Asset"
    upAxis = "{up_axis}"
    metersPerUnit = {mpu}
    doc = "Generated by usdagent from: {description}"
)

def Xform "Asset"
{{
    def Cube "Cube"
    {{
        double size = {size}
        float3[] extent = [(-{half}, -{half}, -{half}), ({half}, {half}, {half})]
    }}
}}
""",
    "sphere": """\
#usda 1.0
(
    defaultPrim = "Asset"
    upAxis = "{up_axis}"
    metersPerUnit = {mpu}
    doc = "Generated by usdagent from: {description}"
)

def Xform "Asset"
{{
    def Sphere "Sphere"
    {{
        double radius = {radius}
        float3[] extent = [(-{half}, -{half}, -{half}), ({half}, {half}, {half})]
    }}
}}
""",
    "cylinder": """\
#usda 1.0
(
    defaultPrim = "Asset"
    upAxis = "{up_axis}"
    metersPerUnit = {mpu}
    doc = "Generated by usdagent from: {description}"
)

def Xform "Asset"
{{
    def Cylinder "Cylinder"
    {{
        double radius = {radius}
        double height = {height}
        float3[] extent = [(-{half}, -{half_h}, -{half}), ({half}, {half_h}, {half})]
    }}
}}
""",
}


def _generate_fallback(
    asset_id: str,
    description: str,
    options: dict[str, Any],
) -> Path:
    """Generate a minimal valid .usda file using string templates (no pxr required)."""
    shape = _detect_shape(description)
    scale = float(options.get("scale", 1.0))
    up_axis = options.get("up_axis", "Y")
    units = options.get("units", "centimeters")
    mpu = _units_to_meters(units)

    # Sanitise description for embedding in the file
    safe_desc = re.sub(r'["\n\r]', " ", description)

    template = _USDA_TEMPLATES[shape]

    if shape == "box":
        size = 100.0 * scale
        half = size / 2.0
        content = template.format(
            up_axis=up_axis, mpu=mpu, description=safe_desc,
            size=size, half=half,
        )
    elif shape == "sphere":
        radius = 50.0 * scale
        half = radius
        content = template.format(
            up_axis=up_axis, mpu=mpu, description=safe_desc,
            radius=radius, half=half,
        )
    else:  # cylinder
        radius = 25.0 * scale
        height = 100.0 * scale
        half = radius
        half_h = height / 2.0
        content = template.format(
            up_axis=up_axis, mpu=mpu, description=safe_desc,
            radius=radius, height=height, half=half, half_h=half_h,
        )

    out_path = ASSETS_DIR / f"{asset_id}.usda"
    out_path.write_text(content)
    return out_path


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_asset(
    asset_id: str,
    description: str,
    options: dict[str, Any] | None = None,
) -> Path:
    """Generate a USD asset file and return its path.

    Uses pxr when available; falls back to string-template generation otherwise.

    Args:
        asset_id: Unique identifier used as the output filename stem.
        description: Natural-language description used for shape detection.
        options: Dict with optional keys: scale, up_axis, units.

    Returns:
        Path to the generated .usda file.
    """
    if options is None:
        options = {}

    _ensure_assets_dir()

    if _PXR_AVAILABLE:
        return _generate_with_pxr(asset_id, description, options)
    return _generate_fallback(asset_id, description, options)
